<Project>
<ItemGroup Condition="'$(RuntimeIdentifier)' == 'android-arm64' or '$(RuntimeIdentifier)' == 'android-x64'"><DotNativePluginEntry Include="VideoPlayerPlugin" /></ItemGroup>
<ItemGroup Condition="'$(RuntimeIdentifier)' == 'ios-arm64' or '$(RuntimeIdentifier)' == 'iossimulator-arm64'"><DotNativeNativeSource Include="$(MSBuildThisFileDirectory)../Platform/iOS/*.swift" /><DotNativePluginEntry Include="VideoPlayerPlugin" /></ItemGroup>
</Project>
